[package]
name = "OmniPlat-backend-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.6" }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
hyper = { version = "0.14", features = ["full"] }
tower = "0.4"